# Generated by Django 4.1.5 on 2023-01-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlist',
            old_name='socaol',
            new_name='social',
        ),
    ]
